### ISSUE TITLE
The "latest release" zip file seems to be corrupted

### ISSUE THREAD

**Issue by Nikovic** [hpi-swa/sandblocks#120]
Greetings.
When trying to open the "latest release" zip, Windows is giving me the error messages "Windows cannot open the folder." and "Windows cannot complete the extraction.", each time with "The Compressed (zipped) Folder '<path\to\sandblocks-all.zip' is invalid."

Maybe you could have a look at this?
Thank you.

**Comment by tom95** [comment]
Hi @Nikovic, thanks for the note! I have now fixed it and uploaded a new release build.

We had some issues with too-long file paths on windows that probably caused this issue here as well.
